fix: updated compile docs
sasjs/cli.sasjs.io pull request #14
Opened 2021-03-15 16:05 UTC by saadjutt01

2021-03-16 06:16 UTC, YuryShkoda requested changes

2021-03-16 06:16 UTC, YuryShkoda commented on docs/compile.md
>  From the root of the project, run:  `sasjs compile`.  This will take all of the macros in the `services` folder and create equivalents in the `sasbuild` folder.
`sasbuild` -> `sasjsbuild`

2021-03-16 06:16 UTC, YuryShkoda commented on docs/compile.md
> +* `--target` (alias `-t`) - The target to use for obtaining the source folders of programs and macros. If it is not specified, the default target will be used, mentioned in `sasjsconfig.json`. The ta
.sasjsrc -> `.sasjsrc`

2021-03-16 06:16 UTC, YuryShkoda commented on docs/compile.md
> +* `--target` (alias `-t`) - The target to use for obtaining the source folders of programs and macros. If it is not specified, the default target will be used, mentioned in `sasjsconfig.json`. The ta
.sasjsrc -> `.sasjsrc`

2021-03-16 06:16 UTC, YuryShkoda commented on docs/compile.md
> +* `--output` (alias `-o`) - path where output of the compiled job or service will be saved. OPTIONAL. If not provided, the output will go to the root of the sasjsbuild folder if in a project (sasjsbu
sasjsbuild -> `sasjsbuild`

2021-03-16 08:48 UTC, saadjutt01 commented on docs/compile.md
>  From the root of the project, run:  `sasjs compile`.  This will take all of the macros in the `services` folder and create equivalents in the `sasbuild` folder.
done

2021-03-16 08:48 UTC, saadjutt01 commented on docs/compile.md
> +* `--target` (alias `-t`) - The target to use for obtaining the source folders of programs and macros. If it is not specified, the default target will be used, mentioned in `sasjsconfig.json`. The ta
done

2021-03-16 08:48 UTC, saadjutt01 commented on docs/compile.md
> +* `--target` (alias `-t`) - The target to use for obtaining the source folders of programs and macros. If it is not specified, the default target will be used, mentioned in `sasjsconfig.json`. The ta
done

2021-03-16 08:48 UTC, saadjutt01 commented on docs/compile.md
> +* `--output` (alias `-o`) - path where output of the compiled job or service will be saved. OPTIONAL. If not provided, the output will go to the root of the sasjsbuild folder if in a project (sasjsbu
done

2021-03-19 05:57 UTC, YuryShkoda approved these changes

2021-03-19 05:57 UTC, merged